version: '3'

services:
  nginx-proxy-manager:
    image: jlesage/nginx-proxy-manager
    container_name: nginx-proxy-manager
    ports:
      - "81:81"
      - "80:80"
      - "443:443"
    volumes:
      - /docker/appdata/nginx-proxy-manager:/config:rw
    restart: always
